#!/usr/bin/env bash

read -p "please enter a number:  " count

if [ $count -eq 42 ] ; then
    echo "42 is correct and the meaning of life:) "

elif [ $count -gt 42 ] ; then
    echo  "too far try again"

else
    echo "too low try again"

fi
