#!/usr/bin/env bash

#Ex15:scripting tests and loops
#1 Write a script that uses a for loop to count from 3 to 7

echo "Bash will count from 3 to 7..."
for i in {3..7}
  do 
     echo "This is $i ";sleep 0.5
 done
